### ISSUE TITLE
CLI reference documentation

### ISSUE THREAD

**Issue by sagikazarmark** [bank-vaults/bank-vaults#2242] opened 2023-09-28 09:10 UTC
Generate CLI reference documentation.

`bank-vaults --help`?

Do we want reference for all commands?

Can cobra help with generation?

**Comment by fekete-robert** [comment] 2023-09-28 10:40
Hi, I've:

- checked `bank-vaults --help`, but couldn't get it to list any commands (it only shows the --delim, file, and template flags for me)

- Cobra can help us, we've used it in other projects before, but when I tried to adopt our generator script (see below) to bank-vaults, it fails because it cannot import the bank-vaults package

`// Copyright (c) 2019, 2020, and 2021 Cisco and/or its affiliates. All rights reserved.

package main

import (
	"fmt"
	"log"
	"path"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra/doc"
	"github.com/bank-vaults/bank-vaults/cmd/bank-vaults"
)

func main() {
	rootCmd.Init("", "", "")

	const fmTemplate = `---
title: %s
generated_file: true
---
`
	const basePath = "/docs/cli/reference/"

	// Customized Hugo output based on https://github.com/spf13/cobra/blob/master/doc/md_docs.md
	filePrepender := func(filename string) string {
		name := filepath.Base(filename)
		base := strings.TrimSuffix(name, path.Ext(name))
		return fmt.Sprintf(fmTemplate, strings.Replace(base, "_", " ", -1))
	}
	linkHandler := func(name string) string {
		base := strings.TrimSuffix(name, path.Ext(name))
		return basePath + strings.ToLower(base) + "/"
	}
	c := cmd.GetRootCommand()
	c.DisableAutoGenTag = true
	err := doc.GenMarkdownTreeCustom(c, ".", filePrepender, linkHandler)
	if err != nil {
		log.Fatal(err)
	}
}
`

**Comment by ramizpolic** [comment] 2023-09-29 07:54
Hi @fekete-robert, I have managed to execute your script as a test case within `cmd/bank-vaults` package. The issue is that the `rootCmd` defined in the same package is not publicly exposed, therefore you are unable to generate docs for it. To enable this (and allow CLI docs generation from other packages), we should make the rootCmd public.

If you (create and) execute the file as e.g. `cmd/bank-vaults/main_test.go` with contents
```go
package main

import (
	"fmt"
	"path"
	"path/filepath"
	"strings"
	"testing"

	"github.com/spf13/cobra/doc"
)

func TestCLI(t *testing.T) {
	// _ = doc.GenMarkdown(rootCmd, os.Stdout)
	const fmTemplate = `---
title: %s
generated_file: true
---
`
	const basePath = "/docs/cli/reference/"

	// Customized Hugo output based on https://github.com/spf13/cobra/blob/master/doc/md_docs.md
	filePrepender := func(filename string) string {
		name := filepath.Base(filename)
		base := strings.TrimSuffix(name, path.Ext(name))
		return fmt.Sprintf(fmTemplate, strings.Replace(base, "_", " ", -1))
	}
	linkHandler := func(name string) string {
		base := strings.TrimSuffix(name, path.Ext(name))
		return basePath + strings.ToLower(base) + "/"
	}
	c := rootCmd.Root()
	c.DisableAutoGenTag = true
	err := doc.GenMarkdownTreeCustom(c, ".", filePrepender, linkHandler)
	if err != nil {
		panic(err)
	}
}
```
It should work without issues.

**Comment by akijakya** [comment] 2023-10-05 15:02
When I built the bank-vaults binary with `make build` and ran `./build/bank-vaults` it gave me a pretty detailed help information btw.

**Comment by ramizpolic** [comment] 2023-11-10 16:39
Marking this as completed since we have the command to generate the necessary CLI documentation.

**Closed by ramizpolic** 2023-11-10 16:39 UTC
